### ISSUE TITLE
Unable to read repository at https://dl.bintray.com/de-jcup/basheditor/content.xml

### ISSUE THREAD

**Issue by Kadsoft2002** [de-jcup/eclipse-bash-editor#108]
Got this error when installing for Eclipse Oxygen. I had to manually install this using the non-secure url:
http://dl.bintray.com/de-jcup/basheditor/

Not working install URL from the Eclipse Marketplace:
https://dl.bintray.com/de-jcup/basheditor/

The error:
Unable to read repository at https://dl.bintray.com/de-jcup/basheditor/content.xml.
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by de-jcup** [comment]
Hello @Kadsoft2002,

thank you for sending this issue.

I had such issues in january 2018 already before, see
https://marketplace.eclipse.org/comment/5143#comment-5143
and
https://marketplace.eclipse.org/comment/5142#comment-5142

It's about the certification prolems and bintray. Seems to be same as your problem - but when I try an installation from my location in germany all is working fine (with HTTPS enabled).

It seems this is a problem I cannot solve by myself, so I have contacted bintray support and tell them about the situation.

When I got an answer/solution I will post it here.

**Comment by de-jcup** [comment]
Hello @Kadsoft2002, 

i entered a ticket at bintray (#78016] Certificate problems at https://dl.bintray.com/de-jcup/basheditor/)
They checked their certificates and those were correct.

So either
- it was temporary problem which is solved now
- you are behind a proxy which has itself not a correct certificate.... 
- you are behind a state firewall ...

There are many people being able to install the plugin via https without any problems. So I think this depends on your configuration/situation or was temporary.

If you don't mind I would like to close the issue
