### ISSUE TITLE
Update site (no marketplace client)

### ISSUE THREAD

**Issue by karypid** [de-jcup/eclipse-bash-editor#109]
Hi,

Is is possible to publish a regular update site? This would allow installing without the marketplace client and also allow installing from command-line with p2-director application.

Thanks

**Comment by de-jcup** [comment]
Hello @karypid , 

**Short answer:** 
Just use https://dl.bintray.com/de-jcup/basheditor as update site

**Some details:** 
There are no special update sites for eclipse marketplace client. It's alway a "regular" update site which must be provided by the solution. The marketplace client just adds the update site to your eclipse installation as you would do by your own. It is just more convenient and does some statistics etc.
