### ISSUE TITLE
No offline installer

### ISSUE THREAD

**Issue by AndrewBrennanCiv** [de-jcup/eclipse-bash-editor#110]
I want to use this on the machine I develop on which is on a closed network.  Since I can't use marketplace to install this because of that, I need an offline installer zip file to install.

**Comment by AndrewBrennanCiv** [comment]
Mark as resolved. Worked easily as any other offline install I've done and it was exactly what I wanted out of this project. Thanks for the quick turnaround.

**Comment by PrasadNutalapati** [comment]
How do we get the offline installation zip for Jenkinsfile editor plugin for Eclipse Oxygen 2018/12 ?

**Comment by AndrewBrennanCiv** [comment]
> How do we get the offline installation zip for Jenkinsfile editor plugin for Eclipse Oxygen 2018/12 ?

Just right click on this link:  [local-basheditor-updatesite.zip](https://github.com/de-jcup/eclipse-bash-editor/files/2030881/local-basheditor-updatesite.zip) and select 'Save link as...' and it will prompt you to save the zip file.

**Comment by de-jcup** [comment]
@PrasadNutalapati Just an additional information: The zip file contains older older plugins (1.5.3) 

To have the newest (2.0.1) plugin in your local upate site you have to follow the instructions contained in README.md (zipfile) and replace the version parts to 2.0.1...
