### ISSUE TITLE
Associate with *. files having #!/usr/bin/env sh

### ISSUE THREAD

**Issue by paulvi** [de-jcup/eclipse-bash-editor#111]
Associate with `*.` files having `#!/usr/bin/env sh`

and I do not know if it is possible at all

![image](https://user-images.githubusercontent.com/1614482/40666050-698cc560-6391-11e8-9dc9-e5cbb59e2093.png)

**Comment by de-jcup** [comment]
![image](https://user-images.githubusercontent.com/11644753/50927098-0c256b80-1457-11e9-92fd-731fd2714be5.png)
