### ISSUE TITLE
 HTTP Proxy Authentication Required

### ISSUE THREAD

**Issue by paulhr** [de-jcup/eclipse-bash-editor#114]
Tested on IE and Chrome.  Tested logged on and not logged on.  Same error during download from the Eclipse Marketplace.
https://marketplace.eclipse.org/content/bash-editor#comment-5548

> HTTP Proxy Authentication Required: https://dl.bintray.com/de-jcup/basheditor/content.xml
> Proxy Authentication Required

**Comment by de-jcup** [comment]
This is not a problem with bintray.com or the marketplace but normally when you are behind a proxy e.g. when you work at a company and the proxy server is between you and internet. You have to define proxy settings for your browsers and also for eclipse when you are in such situation.

Please open your eclipse preferences (Main menu->Window->Preferences) and define a manual proxy setting. Enter your proxy host name and port and setup your credentials like shown in next picture as an example.

![image](https://user-images.githubusercontent.com/11644753/43678293-25ea3da6-9811-11e8-9fc8-5fd39ae5d4ab.png)

**Comment by de-jcup** [comment]
Having nearly two month no repsonse, I close the issue.
