### ISSUE TITLE
No opening curly brace found when there is a valid open and close blocks

### ISSUE THREAD

**Issue by cemroomster** [de-jcup/eclipse-bash-editor#115]
Eclipse complains about a function code, marks function declaration with error message "The function <some_function_name> is not valid because no opening curl brace found". However there is an opening curly brace when declaring function. Please see the code below. 
```
function deploy () {
    arr=("$@")
    for i in "${arr[@]}"; do
        something
    done
}
```
It seems to be impossible to get rid of red X mark from that file and therefore project. 
![screen shot 2018-08-22 at 00 54 53](https://user-images.githubusercontent.com/13966098/44443522-11684380-a5a6-11e8-93f1-b712206a3cfd.png)
![screen shot 2018-08-22 at 00 55 08](https://user-images.githubusercontent.com/13966098/44443523-11684380-a5a6-11e8-9c15-64f382901512.png)

**Comment by de-jcup** [comment]
I will try to fix the parse problem, but currently I am very busy. In the meanwhile you can
turn off the validation by preferences, or change from error to another level (e.g. just warning).

![image](https://user-images.githubusercontent.com/11644753/44844004-fe124380-ac49-11e8-8bc6-da796a6fe2ee.png)

**Comment by cemroomster** [comment]
Will update. Thank you.

**Comment by de-jcup** [comment]
Your wellcome :-)
