### ISSUE TITLE
Dedicated preferences for bash editor to replace tabs by spaces

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-bash-editor#127]
Bash editor preference page shall get an option:
"use custom insert spaces for tabs" boolean

when option is disabled current default text editor handling shall be used.

When enabled a text field for number of spaces shall be editable - with default (maybe 4) and this
shall be used.

**Comment by f18m** [comment]
I experimented a little bit with this and I found it seems to be more difficult than expected :(

I tried:
 - overriding in BashSourceViewerConfiguration the TextSourceViewerConfiguration::getTabWidth and TextSourceViewerConfiguration::getIndentPrefixes functions : no success
 - following http://www.vogella.com/tutorials/EclipseEditors/article.html  I tried to define a custom ContentType for BashEditor - but that does not seem to be the issue: even if BashEditor does not define a custom type the .sh files are opened with the BashEditor plugin class anyway ...

**Comment by de-jcup** [comment]
I have already done a working implementation for my yaml editor which has wanted functionality:

https://github.com/de-jcup/eclipse-yaml-editor/issues/36
https://github.com/de-jcup/eclipse-yaml-editor/issues/9

@f18m : Please try out yaml editor and give me feedback if the setup of yaml editor fullfills your requirements. If so I will just adopt the yaml solution to batch editor as well

**Comment by f18m** [comment]
Ping on this :) 
If you think I can take over some parts of the development, please let me know, thanks!

**Comment by de-jcup** [comment]
@f18m I would suggest to implement it first for yaml editor and then reuse it for bash editor as well (maybe be eclipse-commons approach)
I created an issue for yaml editor:
https://github.com/de-jcup/eclipse-yaml-editor/issues/42
I described there a very generic approach there which can be reused in bash editor.
Also an extra branch is created:
https://github.com/de-jcup/eclipse-yaml-editor/tree/feature-42-tab-to-spaces-on-multiline-selection

So if you don't mind I would suggest you try out to implement https://github.com/de-jcup/eclipse-yaml-editor/issues/42 and I will review the PRs as done for bash editor.
When its working for yaml editor I would transfer the result to [eclipse-commons](https://github.com/de-jcup/eclipse-commons) project and use it in both editors (and maybe more) by the lib.

Setup is same as on bash editor checkout etc. see https://github.com/de-jcup/eclipse-yaml-editor/wiki/Contribution

What do you think?

**Comment by AndrewBrennanCiv** [comment]
I was just about to make a new issue regarding this, thankfully github suggested it when I was filling in the name. This is something I would very much like to see implemented. 

However, I did notice that I was able to get the behavior I wanted by just changing the Eclipse->General->Editors->Text Editors bool of 'Insert spaces for tabs' to true. But I can see why you may want different behavior for Bash editor items themselves.

**Comment by de-jcup** [comment]
@AndrewBrennanCiv The origin idea / wish came from @f18m . 
Its not so easy to adopt a custom behaviour and keeping all "out-of-the-box" goodies (press tab, press shift tab on blocks etc.) when customizing.

**Comment by de-jcup** [comment]
In eclipse-commons 0.5.1 the feature is integrated and can be reused.

**Comment by de-jcup** [comment]
Looks now this way:

![image](https://user-images.githubusercontent.com/11644753/56850275-98717680-6900-11e9-9d36-cc8ef1de259c.png)

**Comment by f18m** [comment]
Looks very nice now! Is this new feature in master branch?

**Comment by de-jcup** [comment]
Hello @f18m ,
sorry that it took such a long time to get the feature back to bash editor - I was very busy.

Yes it's already on **master**, but the implementation is done inside eclipse-commons, so it's reusable. In Yaml Editor your implementation is still as you committed it.

**Comment by f18m** [comment]
Hi @de-jcup ,
I tried out the master branch and I think I found a problem: I'll open a new defect for that since this is closed!
