### ISSUE TITLE
Hyperlink detector allows you to navigate functions only in the selected bash file

### ISSUE THREAD

**Issue by f18m** [de-jcup/eclipse-bash-editor#129]
I think BashEditor plugin would be much more powerful if it could detect functions in all the .sh files you have in your project.
For example I have hundreds of bash functions splitted in several files (each one is a collection of a different category of functions). However when I hold CTRL the BashEditor will not detect as a function call anything that has been defined in a different .sh file...

Do you think it would be possible to implement navigation among different bash files?

**Comment by de-jcup** [comment]
Hmm.. I had this also in mind when I started the editor, but it is not easy. 

# Scenario 
- just collect all functions for all functions inside project
## PRO:
- if there is a include option other than "source" this would work too
## CON:
- slow
- builder necessary (at least for files not opened in editors...)
- not logical coherent

# Scenario 2
- inspect all included "source" parts in current editor
## PRO:
- still simple
- logical coherent (no hyperlink when not possible)
## CON:
- if there is another option to include it would not be inside ...
- Having 
```
File A -> File B
          -> File C
```
File B wil not have possiblity to have hyperlink to FileC functions.
It would work in real live when called by FileA, but opening FileB in editor
it would always have not this parts. Only FileA Editor would have access to all Functions
from B and C (but I would prefer this, it would enforce clean code separation)

## Implementation Scenario2:
### Variant 1
- build model would also scan sources
- building model should also build additional section "externalFunctions"
  - means every "source" include should be parsed in this case (means also build by a model builder and results reused)
  - loop detection necessary (FileA->FileB->FileA...)
- hyperlink detector should use then not only internal functions but also external ones

###  Variant 2
 - same as Variant 1 but build external functions always on hyperlink target call ?
  
## Additional
- Creating a model could also result in having easy impl for code completion for external functions
-

**Comment by f18m** [comment]
Hi @de-jcup ,
thanks for the very complete answer.

Honestly for me scenario 2 would be mostly useless for the reason that you pointed out very clearly:

```
File A --> File B
File A --> File C
```

I have plenty of cases where from file B I call functions written in file C. The reason in my case is that the functions are inter-dependent and in different files mostly for readability (they are organized in different categories).
I think that this use case will be very common with Bash given that it does not really support a OOP model and function hiding (i.e. the equivalent of Java/C++ "private" keyword).

I also would like to mention that other editors with Atom do implement scenario 1: the bash plugins don't even try to be so smart to check what's included by each file, they just scan whatever Bash file is available in the directory you open.
I think this also happens with Eclipse CDT: if I open as a single Eclipse project a folder where I build with a GNU makefile several different command-line utilities and then I hit CTRL and I click on the "main" function (of course each utility has its own, so I have like 10 different "void main"), I get a disambiguation dialog which asks me which of the 10 different "main" functions I want to visit...

All of this just to say that I think BashEditor should not try to "do too much" and simply provide a navigation among all functions of the project and let the developer care about actual code correctness (and eventually disambiguate the function to navigate to in case of multiple functions with the same name being present)...

**Comment by de-jcup** [comment]
Hmm. I will give it a try. I think I can approve this like I have done for task support in eclipse-commons by using IResourceChangeListener and a global project specific model.

What would you prefer ?
a) editors can only link to functions for *.sh files in same folder
b) editors can link to functions for *.sh files in same project
( I would prefer b) it's easier to implement)

**Comment by f18m** [comment]
Hi @de-jcup ,
I think solution b) is indeed the best one, and the most user-intuitive one.

Thanks for taking care of this! If you need help with some parts of this feature, let me know!

**Comment by de-jcup** [comment]
Model building for a combined model for complete project can be done when
https://github.com/de-jcup/eclipse-commons/issues/9
is implemented

**Comment by f18m** [comment]
Hi @de-jcup ,
let me know if I can help with something for this issue. This would be really a game-changing feature for me and other colleagues, thanks!

**Comment by de-jcup** [comment]
Hi @f18m , thank you. I just closed https://github.com/de-jcup/eclipse-commons/issues/9 - model builder concept is now working inside commons library.

So it should be pretty easy to implement for somebody knowing the commons library approach (at least myself). So I moved this issue back to mileston 2.1.0 and try to implement it. If there is a way you can support me I will give you feedback.   

If you are interested to do some of the other issues:
https://github.com/de-jcup/eclipse-bash-editor/milestone/26
this would be very cool. For example: 
https://github.com/de-jcup/eclipse-bash-editor/issues/141#issuecomment-491250052
would be helpful...

**Comment by de-jcup** [comment]
It is already working ...

![image](https://user-images.githubusercontent.com/11644753/57561114-4150b480-738a-11e9-9339-1652d91c742b.png)

**Comment by de-jcup** [comment]
In preferences user has now possibility to
- turn off shared model build (means model is no longer build, also only script function linking works)
- setup link function strategy when shared model is build:
  * Script: even when functions with same would be available the links of current script are only used as links 
  * Project scope: If script has not this function inside provide links to all such named functions in bash scripts inside project
  * Workspace scope: If script has not this function inside provide links to all such named functions in bash scripts inside complete workspacet

![image](https://user-images.githubusercontent.com/11644753/57575413-0615ba80-744a-11e9-8b4f-ac5f83198eea.png)

**Comment by de-jcup** [comment]
Some changes in eclipse-commons 0.7.0 must be applied here

**Comment by de-jcup** [comment]
@f18m Just deployed bash editor v2.1.0 on marketplace. Contains the feature...

**Comment by de-jcup** [comment]
@f18m : There is also now a youtube video available, showing the feature and how to use : https://youtu.be/RNNnLEBc-ys

**Comment by f18m** [comment]
@de-jcup : I tried out the feature today directly at office and it worked just fine, very good work thanks!! I suggested all my colleagues to upgrade to the new version, very useful and time saving!
