### ISSUE TITLE
escape of '\' in case error

### ISSUE THREAD

**Issue by jkraskesis** [de-jcup/eclipse-bash-editor#130]
The following piece of code gives a "This 'case' is not correct closed. A 'esac' is missing" error. 

#!/bin/bash
case "foo" in
	foo*)
		SEPARATOR="\\"
		;;
esac

**Comment by de-jcup** [comment]
Tried out in bash by setting a variable in this way resulted in ongoing string too:
![image](https://user-images.githubusercontent.com/11644753/51477511-feda7c00-1d88-11e9-99bd-e6daaf94418a.png)
Using `\\` works: 
![image](https://user-images.githubusercontent.com/11644753/51477547-1580d300-1d89-11e9-8404-14e45e9316b1.png)

**Comment by de-jcup** [comment]
So changing example to use \\ instead - results still in an error:
![image](https://user-images.githubusercontent.com/11644753/51477610-43feae00-1d89-11e9-94c9-3805a74c3a4d.png)

> This 'case' is not correct closed. A 'esac' is missing

But this one should be valid. So marking as bug.
@jkraskesis - in the mean while until fixed you can set in preferences to use error level
warning for those ones - so you get rid of potential project build errors... see picture:

![image](https://user-images.githubusercontent.com/11644753/51477919-25e57d80-1d8a-11e9-91a5-7213e4af4d21.png)

**Comment by jkraskesis** [comment]
You were right. I made a copy&paste error: the error was about "\\" (2 backslashes) and NOT about "\" (1 backslash). Thanks for looking at it!
