### ISSUE TITLE
Debugger should have function keys for debugging as in java

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-bash-editor#141]
Would like to have F6 for step into etc. as hotkeys.
Currently no keys are defined

**Comment by arrmo** [comment]
Yes, seeing this ... :-). I see an x-term open ... how to step through the code from there? I have hunted around, not seeing it (but it may be me!). How to walk through the code (i.e. single step)?

Thanks!

**Comment by de-jcup** [comment]
Have you seen the video? https://www.youtube.com/watch?v=RADZtPY_rCQ&list=PLaBYAz_I_8tF7sZVIcUv8zOVe2RMiWn-L&index=6&t=0s or look at 
https://github.com/de-jcup/eclipse-bash-editor/wiki/Debugger#video

You just need to click on the debug step icons:
![image](https://user-images.githubusercontent.com/11644753/55377414-25e5c480-5515-11e9-9c3f-39cb5172ba6c.png)

If you do not see the step icons on the debug view just use the pulldown menu inside the view and make the debug toolbar visible

**Comment by arrmo** [comment]
Yep, the default wasn't showing the Debug perspective. Would it make sense to (optionally?) have this happen automatically? Thanks!

**Comment by de-jcup** [comment]
You can already enable this inside preferences:

![image](https://user-images.githubusercontent.com/11644753/55463082-8a2d8480-55f8-11e9-882e-e43b3059b42a.png)

**Comment by de-jcup** [comment]
By the way: You do not need to show the debug perspective, it's also enough to show just the Debug view by 
`Window->Show View->Other...` and select debug view:
![image](https://user-images.githubusercontent.com/11644753/55463383-37a09800-55f9-11e9-9c1e-08c64b69437e.png)

When using only debug **view** you have to enable the debug toolbar as described before, because its normally disabled.

![image](https://user-images.githubusercontent.com/11644753/55463479-73d3f880-55f9-11e9-9f99-7f4ef3e8ea1a.png)

**Comment by arrmo** [comment]
Thanks for the pointers!

**Comment by de-jcup** [comment]
The problem seems to be the context.
The default shortcuts are defined for "Debug" context id and not for the debug context id used by bash editor.

Solutions:
-----------
So either adding own commands/accelerators in plugin.xml or also use context "Debug"

Using own commands/accelrator settings would be more clean because having own scope/context for bash debugging would be nice.
But if too much effort a reuse of "Debug" could be an option too...

**Comment by de-jcup** [comment]
Interesting keybindings were found at https://github.com/eclipse/eclipse.platform.debug/blob/master/org.eclipse.debug.ui/plugin.xml
