### ISSUE TITLE
Please build out functionality of the Outline view

### ISSUE THREAD

**Issue by jlczuk** [de-jcup/eclipse-bash-editor#143]
#nice-to-have

It would be fantastic if the Outline view could be enhanced by showing where variables are declared.  Functions could be expandable to show variables in their scope.  Additionally, when double clicking a variable or function name, showing the ghost marks for the locations of other occurrences in the bar to the right of the editor window scroller would be helpful too.

**Comment by de-jcup** [comment]
Hello @jlczuk I will try to implement showing variable definitions in outline

The ghosting... I must see if this is easy to implement. If not I will create another issue

**Comment by de-jcup** [comment]
Created #148 so ghosting will be done in another issue but this issue would be a precondition.

**Comment by de-jcup** [comment]
Looks currently like this:

![image](https://user-images.githubusercontent.com/11644753/56876462-d7f6aa80-6a47-11e9-81d4-57cffec11956.png)

**Comment by jlczuk** [comment]
Looks good!  I like the twisty mechanic for variables local to a function.  I would expect the behavior to be:

1. When my cursor is on or in the function, it is highlighted in the outline.
2. When I select the function or variable in the outline, the current line moves to the declaration of that function or variable.

**Comment by de-jcup** [comment]
It's already implemented in such way - but one trade off is: Global variables are linked only at the first position inside the script (just first found by line numbers).

I am having the positions about the other usage of the global variables, but I do not want to fill up all references but have only ONE appearence inside editor.

In #148 i could try to do the ghosting or maybe a "call reference" for the variables.

Nice benefit: With this issue #151 should be easily to implement.

**Comment by de-jcup** [comment]
If a user does not want variables inside outline/quick outline it can now be easily turned off (enabled per default) :
![image](https://user-images.githubusercontent.com/11644753/56998617-2a50dc00-6bac-11e9-94ab-4ea9e6ab3174.png)
