### ISSUE TITLE
New Project

### ISSUE THREAD

**Issue by arrmo** [de-jcup/eclipse-bash-editor#144]
Sorry, likely stupid on my part, but ... I can't seem to create a new bash-editor project - it's not in the list. Am I just missing how to start this up?

Thanks!

**Comment by arrmo** [comment]
OK, it looks like you just create a Generic project, then control launch to enable bash debugging ... do I have that right? Thanks!

**Comment by de-jcup** [comment]
Hello @arrmo , "bash editor" is only an editor for bash files - so you do not need any special project. You can use any project you like.

**Comment by arrmo** [comment]
OK, thanks. Couldn't get the debugger working without setting up a (Generic) Project, but then it worked. Thanks!
