### ISSUE TITLE
X-Window Error

### ISSUE THREAD

**Issue by arrmo** [de-jcup/eclipse-bash-editor#145]
Hi,

Getting the X-Window error below - is this a known issue (on Ubuntu 18.10)? FYI, X-Windows is working fine other than this issue. And this happens when trying to launch a debug session.

```
(WebKitWebProcess:14047): Gdk-ERROR **: 12:12:55.019: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadFBConfig'.
  (Details: serial 153 error_code 163 request_code 149 (GLX) minor_code 21)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
# Error constructing proxy for org.gnome.Terminal:/org/gnome/Terminal/Factory0: Could not connect: Connection refused
result:1
```

Thanks!

**Comment by de-jcup** [comment]
Hm. I am using Mint Linux, which is based on Ubuntu.
Does the terminal call work and you have just some logs inside a linux log file, or does opening the terminal not work at all?

**Comment by arrmo** [comment]
Mainly / just the info above - or are you looking for more detail than this? Thanks!

**Comment by de-jcup** [comment]
Hello @arrmo ,
at [Debugger configuration](https://github.com/de-jcup/eclipse-bash-editor/wiki/Debugger#configuration) I described how you can setup the terminal launch. 

### Please do following:
#### Catch Meta information
- enable "show meta information in debug console" and make sure you opened the console view ("Windows->Show views->Console" )
- In preferences for debugger there is a test button. Please click this button, It will launch
  a very simple, generated bash script in temp folder
- now you should be able to see call information, how the bash script was launched 
- inspect the command and try call inside a terminal
- post relevant part at this issue
#### Try out in console
Look at catched meta information and evaluate the call. Open a console and try out the call standalone from eclipse.

**Comment by arrmo** [comment]
Got it working! Forced a video driver update, then it was OK. Thanks!

BTW, debugging starting now - how do I see the value of variables assigned within my script? I don't see them in the Variables list, but I may be doing something wrong.

**Comment by de-jcup** [comment]
At the picture you will see the variables view - its automatically shown (same as breakpoints) when you are opening the debug perspective. Of course you can also show the view "Variables". It shall show all variables which are currently available inside your current debug session. Variables are only shown when the debugger has passed a line where the variable was defined. In the example "variable2=42" was already passed and so shown at "Variables" view:

![Screenshot](https://user-images.githubusercontent.com/11644753/53704592-39224900-3e1e-11e9-93e4-5720305596e2.png)
