### ISSUE TITLE
block indentation does not use spaces if "Replace strategy" is set

### ISSUE THREAD

**Issue by f18m** [de-jcup/eclipse-bash-editor#153]
Using latest master as of today (355898e7863766502465ac81586acecc3e9904bd), I did set the "Replace strategy" to "Always, with custom space amount" and "Amount of spaces" to 4.

Then I write some bash code, I create a multiline selection and hit TAB: expected result is: the block is indented using 4 spaces. Actual result: I see each line prefixed with 4 spaces + 1 TAB character (each line). The result is that the block of code is indented 2 levels and with mixed spaces/tabs!!

**Comment by de-jcup** [comment]
Hello @f18m, you are right. The problem is inside eclipse-commons library. 
Will create an issue there, fix it and use new lib version.

Thanks for reporting this.

**Comment by f18m** [comment]
Confirmed it works perfectly now! Looking forward for next Bash-editor release then :)
