### ISSUE TITLE
Source not found - Select Bash script when debugging Java code

### ISSUE THREAD

**Issue by gitdode** [de-jcup/eclipse-bash-editor#164]
Since Bash Script Editor is installed, when debugging Java code and when source is not found because it is not in the Java source lookup path, the editor shows "Source not found" and a button "Select Bash script" instead of "Edit Source Lookup Path".

![image](https://user-images.githubusercontent.com/11530253/57759922-0ab4ca00-76fb-11e9-930e-b8d2fa9c743b.png)

When uninstalling Bash Script Editor again, this works as usual. Is there any setting like file associations that can be adjusted?

This happens in Eclipse IDE for Enterprise Java Developers
Version: 2019-03 (4.11.0)
Build id: 20190314-1200

I remember this issue didn't occur in an earlier version of Eclipse/Bash Script Editor.

**Comment by de-jcup** [comment]
Hm. tried out with JDT Eclipse 4.10 and 4.11.0 works without problems.

I think I remember about having such an issue myself once, but I am not able to reproduce it any longer.

So some questions:
- Which version of bash editor do you exactly use?
- Have you tried a restart?
  * does this happen on every start or ony sometimes?
- Have you another installation where this does not happen?
- Does this happen only in a special constallation?
  * I tried to differ between first debugging bash then java and then I tried first debugging java, then
    bash debugging. I am always getting the correct editor
- I am using Linux. Which OS do you use?
- Which Java Version do you use?

**Comment by de-jcup** [comment]
Forget my questions, I will remove my own "NotFoundEditor" implementation and support the standard editor from eclipse debug environment. This will be amore clean and correct way.

**Comment by de-jcup** [comment]
Hmm.. while imlemeting this and bringing up default SourceNotFound editor for bash scripts available too, i found out it has a little bit odd behaviour - IMHO.

When you have used an absolute file as `source`, its not found in workspace and you got the editor opening. When you now want to add the resource by file system you should not try to to set the
folder where the source resides, but instead use `/` instead:

![image](https://user-images.githubusercontent.com/11644753/57801725-aa527680-7754-11e9-83d3-0759c7f5d1fb.png)

I found this a little bit odd and created a ticket:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=547327

**Comment by gitdode** [comment]
Great, that was a quick fix! Looking forward to the next release.

Cheers,
Torsten

**Comment by de-jcup** [comment]
@gitdode : v2.2.0 is released and contains the fix.

**Comment by gitdode** [comment]
Update, restart - works! Thank you!

![image](https://user-images.githubusercontent.com/11530253/58157290-42ca8880-7c78-11e9-816d-20f3bd6da011.png)
