### ISSUE TITLE
Invalid parsing of escape sequences in single-quoted strings

### ISSUE THREAD

**Issue by andyg1001** [de-jcup/eclipse-bash-editor#175]
I'm running the latest release 2.2.1.  The syntax highlighter is incorrectly assuming that the back-slash character introduces escape sequences in single-quoted strings.  This is not true in bash (see https://www.linuxjournal.com/content/bash-quoting for further details).

For example the following is incorrectly handled:

```
  for a in 1 2 3; do
    echo '\'
  done
```

"done" appears to be still part of the string and "do" is underlined with the complaint "This 'do' is not correct closed. A 'done' is missing."

**Comment by de-jcup** [comment]
It is not only a bug inside syntax highlighting, but also inside parsing - means ending done is not recognized and handeld as an error: 

![image](https://user-images.githubusercontent.com/11644753/65947634-05051a00-e439-11e9-80a8-5c57985df38a.png)

The script before is correct and does print 3 lines with `\`

**Comment by de-jcup** [comment]
Is now fixed for syntax highlighting and also parsing:

![image](https://user-images.githubusercontent.com/11644753/65950578-9e82fa80-e43e-11e9-849f-6fe87cf70928.png)
