### ISSUE TITLE
Popup help has no text formatting

### ISSUE THREAD

**Issue by jrheisey** [de-jcup/eclipse-bash-editor#177]
When I hover over an 'if' command in my script and the pop up help appears, the section titled "Offline description:" has the description as one long string of characters with no formatting applied.

**Comment by de-jcup** [comment]
I tried out with
- Bash Editor 2.2.2
- Eclipse 4.12
- Linux (Ubuntu based)

Had no problems.

Please provide me with more information:
- Bash Editor Version
- Eclipse Version
- Operation System

**Comment by de-jcup** [comment]
I also tried out on a windows 7 machine:

![image](https://user-images.githubusercontent.com/11644753/66833781-b7220300-ef5c-11e9-8b35-ceca73b429a7.png)
