### ISSUE TITLE
Erroneous error: It seems this closing bracket is missing a opening one

### ISSUE THREAD

**Issue by milindrao** [de-jcup/eclipse-bash-editor#184]
I'm using version 2.2.3 of the Bash Editor in 
Version: 2019-09 R (4.13.0)
Build id: 20190917-1200

> function copyArtifactToAllServers()
> {
> 	ARTIFACT=$1
> 	for ((i=0; i < NUM_FRONTENDS; i++)); 
> 	do
> 		scp -q -o StrictHostKeyChecking=no $ARTIFACT $USER@${fe_servers[$i]}:$UPGRADES_FOLDER
> 	done
> 	
> 	for ((i=0; i < NUM_BACKENDS; i++)); 
> 	do
> 		scp -q -o StrictHostKeyChecking=no $ARTIFACT $USER@${be_servers[$i]}:$UPGRADES_FOLDER
> 	done
> }

I get the error that the closing bracket is missing on the scp lines.  It gets confused by the $i in the square brackets.
> {fe_servers[$i]}

**Comment by de-jcup** [comment]
![image](https://user-images.githubusercontent.com/11644753/77183679-0271ac00-6acf-11ea-8bf4-a19f7409957b.png)

**Comment by de-jcup** [comment]
Fixed problem, looks now like:

![image](https://user-images.githubusercontent.com/11644753/81481108-ec11e200-922d-11ea-85f9-59fc5c2aeb62.png)

Will be available in Version 2.3.0
