### ISSUE TITLE
Editor syntax error reported with regular expression containing brakets

### ISSUE THREAD

**Issue by jeanma06** [de-jcup/eclipse-bash-editor#186]
Hi All;

When using regular expression in If condition, the syntax is as follow:

if [[ "StringValue" =~ regexp ]]
then
fi

Note that the regular experssion is not quoted and this is what we want.

example

if [[ "$MyValue" =~ ^-e.* ]]
then
echo "start with "-e"
fi

In the case the regular expression contains a bracket sign, the editor reports an error like in the code below

if [[ "${PAARMSS[$((idx+1))]}" =~ ^[[:space:]]{.$ ]]
then
echo Here
fi

the attached capture show the error in the editor.

![Capture](https://user-images.githubusercontent.com/64248942/80185996-9aead700-860d-11ea-8eb6-31f0aef43e4f.JPG)

Best regards;
Jean-marie

**Comment by de-jcup** [comment]
Is now fixed, comes with Version 2.3.0

![image](https://user-images.githubusercontent.com/11644753/81482252-e3250e80-9235-11ea-958c-0d3f9d21c994.png)
