### ISSUE TITLE
Text in HereDoc is interpreted

### ISSUE THREAD

**Issue by kwinner-4spiegel** [de-jcup/eclipse-bash-editor#196]
Hi,

first off - thanks for this great plugin!
Now to my issue - I use a shell-script to create java-classes from DB entries. In short I have this snippet:

`
#!/bin/bash

[DOSTUFF]

cat << -EOT
String text = "Sometext " + st.getval() + " ${somevar}. This is the end";
-EOT

[DOMORESTUFF]
`
The plugin now complains that st.getval() is invalid, since no curley brackets found...
The part output as hereDoc should actually be output (to file or screen), but not ran as shell-code (in my case, it's actually Java-code).
Strangely, there's a quickfix: put a blank in the brackets of st.getval( ) - but the actual problem is, that the hereDoc *should* contain text, not to-evaluate (as bash-syntax) code. OTOH, in some circumstances, it *could* contain code the user of the plugin wants evaluating (in that case comment the cat << -EOT & -EOT and verify your text is correct code ;) ).

**Comment by de-jcup** [comment]
![image](https://user-images.githubusercontent.com/11644753/83928373-dd1c4200-a78f-11ea-9398-97543cb33d11.png)

**Comment by de-jcup** [comment]
After last commit:
![image](https://user-images.githubusercontent.com/11644753/83928511-59168a00-a790-11ea-97b6-754b560c491f.png)
