### ISSUE TITLE
Manual installation

### ISSUE THREAD

**Issue by seekM** [de-jcup/eclipse-bash-editor#201]
Unfortunately, due to external circumstances I can't use Eclipse->Help->Eclipse Marketplace...  to install eclipse-bash-editor. Is it possible to download the source code from this repository and install it manually? If it is, could you maybe give instructions how to do this? I couldn't find anything via google. Thanks!

**Comment by de-jcup** [comment]
Please look at 
https://github.com/de-jcup/eclipse-bash-editor/wiki/FAQ#how-can-i-install-bash-editor-offline
to create an offline install.

If you want to build the plugin locally by your own, please follow instructions at
https://github.com/de-jcup/eclipse-bash-editor/wiki/Contribution
