### ISSUE TITLE
Syntax parser does not correctly recognize escaped characters

### ISSUE THREAD

**Issue by steffen-heil** [de-jcup/eclipse-bash-editor#202]
The following is parsed incorrectly:

    function errorCodes {
        echo 'test'\''test'
    }

This leads to incorrect syntax highlighting and to an error marker that the function would not be completed.

**Comment by de-jcup** [comment]
Yes, you are right its a bug.
![image](https://user-images.githubusercontent.com/11644753/85073515-3a19ee00-b1bb-11ea-9d17-37ce5505dfa0.png)
