### ISSUE TITLE
Cannot use windows 10 bash

### ISSUE THREAD

**Issue by steffen-heil** [de-jcup/eclipse-bash-editor#203]
The code seems to be fixed to convert Windows paths to `/C/...`, but the Windows bash is using `/mnt/C/...`,  It should be configurable, where the temporary files are stored and how they can be reached.

**Comment by de-jcup** [comment]
Please refer to https://github.com/de-jcup/eclipse-bash-editor/issues/155 - I think this was already fixed but you havent configured as described at the issue.

**Comment by steffen-heil** [comment]
Well, my last test was some time ago and I don't exactly recall what I changed. I tested it again right now and it does actually start my script, but it does NOT stop on breakpoints. I believe the mapping is the problem, as my script is not located in my home directory, not even on the same drive letter.

**Comment by de-jcup** [comment]
When I do bash debugging , my script code is inside a dedicated eclipse project, available in workspace.

So I would suggest to create a eclipse project containing your scripts and try again.

**Comment by de-jcup** [comment]
@steffen-heil  there is #226 , maybe this is related? You haven't answered my last suggestion - so I hope this fixed your problem and close this issue now.
