### ISSUE TITLE
Syntax highlighting for initializing boolean variables

### ISSUE THREAD

**Issue by Fruchtzwerg94** [de-jcup/eclipse-bash-editor#204]
Syntax highlighting of boolean values initializing variables only works with spaces, which is invalid syntax.
![grafik](https://user-images.githubusercontent.com/29866610/85106124-f4d1dc80-b20b-11ea-9d1f-40aae953b1c5.png)
Correct syntax does not support the syntax highlight.

**Comment by de-jcup** [comment]
After bugfix highlighting for correct syntax is now correct:
![image](https://user-images.githubusercontent.com/11644753/88229634-5ce36a80-cc71-11ea-9bfe-52acc6a6c35a.png)
