### ISSUE TITLE
Parsing / Escaping Issue

### ISSUE THREAD

**Issue by hubick** [de-jcup/eclipse-bash-editor#209]
Hi,

My [script](https://github.com/de-jcup/eclipse-bash-editor/files/4985193/test.sh.txt) seems to be causing an error with the parsing...

![eclipse-bash-editor_parse](https://user-images.githubusercontent.com/599638/88602939-12773a80-d031-11ea-9789-d884e05d0192.png)

The script seems to work fine.

Sorry I can't provide a better title, as I'm not sure what exactly is going wrong.

Much Thanks.

**Comment by de-jcup** [comment]
Hello @hubick ,

please do me a favor and provide a bash snippet example - except a PNG - and add it as a comment to this issue. So I can add it to test suite, write a test etc.

**Comment by hubick** [comment]
That's what the "script" link is :-) https://github.com/de-jcup/eclipse-bash-editor/files/4985193/test.sh.txt

**Comment by de-jcup** [comment]
Last commit did fix the problem and also improved the highlighting for variable assignments of code execution:

![image](https://user-images.githubusercontent.com/11644753/91104144-78290780-e66d-11ea-9dc6-faeb72157fda.png)

**Comment by hubick** [comment]
Thank you!

**Comment by de-jcup** [comment]
@hubick - I just release version 2.5.0 on eclipse marketplace containing the fix.

**Comment by hubick** [comment]
Updated and it works great! Now I can use the Outline to navigate my whole script too! Thanks again! :-)
