### ISSUE TITLE
${var%'\'} expression is not parsed correctly

### ISSUE THREAD

**Issue by amurashkin17** [de-jcup/eclipse-bash-editor#211]
It seems that `${var%'\'}` expression is not parsed correctly. For example, the short script below has the following error in the first line.

**This do is not correct closed. A 'done' is missing.**

```
while read line; do
    a=${var%'\'}
done
```
Another error here.

**It seems this opening bracket is missing a closing one.**

```
function f {
    a=${var%'\'}
}
```

The workaround is to use  `"\\"` instead.

```
while read line; do
    a=${var%"\\"}
done
```

**Comment by de-jcup** [comment]
With last commit the parsing is now correct:

![image](https://user-images.githubusercontent.com/11644753/91170829-c673f000-e6d9-11ea-9b5d-e697a57fe513.png)
