### ISSUE TITLE
Do not show functions from backup files

### ISSUE THREAD

**Issue by amurashkin17** [de-jcup/eclipse-bash-editor#212]
When using "hyperlinking" feature, functions from all files are shown including backup files. Like

> Opens external declaration of Func from file.sh
> Opens external declaration of Func from file~

It happens even the backup files are not listed in Project Explorer view.

It would be nice if backup files can be excluded. For example, if the filenames match specific patterns.

**Comment by de-jcup** [comment]
`*.bak `files are currently already not used for hyperlinking. 

But filenames having ~ at the end are currently accepted (like described):

![image](https://user-images.githubusercontent.com/11644753/109400997-56764900-794c-11eb-9889-076c5d8e41be.png)

As this is a standard for Linux (e.g. when VIM opens a file a backup is created with ~ at the end), this shall be filtered automatically.
