### ISSUE TITLE
Not working with Git Bash or MSYS2 Bash in windows

### ISSUE THREAD

**Issue by dickensas** [de-jcup/eclipse-bash-editor#215]
When  I check the bash is installed or not using where command, I see below output

`C:\>where bash`
`C:\Program Files\Git\bin\bash.exe`

When I check the version  I get

`C:\>bash --version`
`GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)`
`Copyright (C) 2016 Free Software Foundation, Inc.`
`License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>`

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.`

When I check the Eclipse Launch properties for Bash Editor plugin I see

`cmd.exe /C ${BE_TERMINAL}`
`start "${BE_CMD_TITLE}" cmd.exe /C bash --login -c '${BE_CMD_CALL}'`

"Test Terminal" is working fine

`519`
`A simple test`
`-a 1 -b`
`Exit code=1`
`Press enter to continue...`

But when I run a shell script it keeps on saying

`Launching delegate` ..... 57%

it never runs

**Comment by de-jcup** [comment]
I tried on a my windows machine - having same problem as you described. Marked as a bug - will be fixed.

**Comment by de-jcup** [comment]
Also annoying: 
- It is not possible to terminate launch progress (pressing the red button has no effect).
- no log information available, so necessary to develop / fix this at windows, currently no way to get enough information to fix this at my linux environment

**Comment by de-jcup** [comment]
Preparing a fresh windows setup for myself for testing/fixing:

- git 2.28.0 for windows (32bit) from https://git-scm.com/download/win
- windows 10 home

For easier setup I used "git and optional linux tools" at installer wizard page:

![image](https://user-images.githubusercontent.com/11644753/90990418-8b6ea100-e5a1-11ea-8d2f-bbbfc313e717.png)

**Comment by de-jcup** [comment]
With last commit launch does now work again with windows (10). 

Unfortunately the temporary files were the process IDs are written to - used for terminate terminals - are defined in windows style and so not usable inside termination scripts - must be fixed inside `BashDebugCodeBuilder`.

Maybe a good choice would be to use users home folder instead of temp folder? So we could use `~/basheditor_terminal_pid4port_3331.txt` . Or we could transform to unix style way - mingw : `C:\\somewhere\xyz.txt` to `/c/somewhere/xyz.txt`

**Comment by de-jcup** [comment]
@dickensas - I just released version 2.5.0 on eclipse marketplace and tested with latest eclipse for java: https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2020-06/R/eclipse-java-2020-06-R-win32-x86_64.zip

All is working fine now - if you don't see the debug view on start, please read 
https://github.com/de-jcup/eclipse-bash-editor/wiki/Debugger#i-cant-see-the-debug-and-breakpoint-view
