### ISSUE TITLE
Sort Outline

### ISSUE THREAD

**Issue by numeralnathan** [de-jcup/eclipse-bash-editor#231]
In the Eclipse Outline, please add a feature to sort the variables and functions alphabetically with variables listed first and functions listed after.

For large scripts, this will make it faster for me to find the variable or method faster.

**Comment by de-jcup** [comment]
When you are opening the quick outline ( `CTRL`+ `o`) you can simply start typing to filter - like shown in next picture: 

![image](https://user-images.githubusercontent.com/11644753/119283460-76f92b00-bc3d-11eb-8920-a5f49deb2196.png)

Does this already help you or do you think the alphabetical sort is still necessary ?

**Comment by numeralnathan** [comment]
Alphabetical sort is still necessary.  It will allow me to move my mouse and scroll to the item I am looking for.

Without this feature, I have to grab my mouse, click on the search field, move my hand back to my keyboard and type.  This is much more cumbersome and slow.

**Comment by de-jcup** [comment]
The former commit added alphabetical sorting function inside outline view. A sorting button was added to outline view toolbar which can be toggled.

## Without alphabetical sorting
![image](https://user-images.githubusercontent.com/11644753/125965766-883373a2-538a-49ba-9d97-913d0431f3f7.png)

## With alphabetical sorting enabled
![image](https://user-images.githubusercontent.com/11644753/125965931-e1195c20-96d6-4bc5-aaa1-aa53e1171c8e.png)

## Default preferences for editor
The default state can be defined in preferences. Per default the alphabetical sorting is enabled, so on new opened editor the outline will be always sorted. If not wanted this can be changed:
![image](https://user-images.githubusercontent.com/11644753/125966748-1f590d6d-7cad-41b8-816d-a77bb1aaec15.png)

**Comment by de-jcup** [comment]
Must reopen issue, because

1. bigger test script is not sorted per default on startup (see picture 1)
2. bigger test script is not grouping functions (see picture2) when sort is done manually

Picture 1:
![image](https://user-images.githubusercontent.com/11644753/126011275-d4dda82e-9b6d-492c-98c9-3d98b3df20ea.png)

Picture 2:
![image](https://user-images.githubusercontent.com/11644753/126011328-b1d2298c-6f67-49a3-8320-abb9134eb0a2.png)

**Comment by de-jcup** [comment]
Last commit fixed former mentioned category and initial sorting problem:

![image](https://user-images.githubusercontent.com/11644753/126012510-747b8c2c-eca5-4406-bcae-7da581f83663.png)
