### ISSUE TITLE
Keywords not highlighted with metacharacters without spaces

### ISSUE THREAD

**Issue by rmdefi** [de-jcup/eclipse-bash-editor#234]
Using bash-editor 2.6.0

Keywords are not highlighted when they are prefixed or suffixed by a metacharacter without spaces.

Examples (note that github does the highlighting as expected):

```bash
# in this example, neither are highlighted
read;exit
# here, only read is highlighted
read ;exit
# here only exit is highlighted
read; exit
# here both are highlighted
read ; exit
```

The problem is the same if you replace the semicolon by another metacharacter (like & or |).
Those spaces are not required, as metacharacters separate words.

(note that it is different for curly braces, which are reserved words and must be separated by blanks)

**Comment by de-jcup** [comment]
Yes, this is a bug:
![image](https://user-images.githubusercontent.com/11644753/117623422-11ed0200-b174-11eb-86ea-2a70001ba616.png)

**Comment by de-jcup** [comment]
TODO : Change word end detector to accept not only whitespaces but also:
- ";"
- "&"
- "|"

**Comment by rmdefi** [comment]
Note that, according to bash's documentation, '(' ')' '<' and '>' are also metacharacters:

>  'metacharacter'
>       A character that, when unquoted, separates words.  A metacharacter
>       is a 'space', 'tab', 'newline', or one of the following characters:
>       '|', '&', ';', '(', ')', '<', or '>'.

Thank you

**Comment by de-jcup** [comment]
![image](https://user-images.githubusercontent.com/11644753/126011124-48947442-56c0-41f2-a529-bf95e97296b9.png)
