### ISSUE TITLE
Install on Isolated Network

### ISSUE THREAD

**Issue by descenter2000** [de-jcup/eclipse-bash-editor#235]
The system I work on does not have internet access.
This looks like a great tool. How can I install it to my system.

**Comment by de-jcup** [comment]
Please look at https://github.com/de-jcup/eclipse-bash-editor/issues/110

**Comment by de-jcup** [comment]
This is also answered inside wiki: https://github.com/de-jcup/eclipse-bash-editor/wiki/FAQ#how-can-i-install-bash-editor-offline 

So I close this issue.
