### ISSUE TITLE
request: configurable indent / tab width

### ISSUE THREAD

**Issue by sebalis** [de-jcup/eclipse-bash-editor#244]
A request: It would be great if Bash Editor could be configured to use tabs (of a configurable with) or a configurable number of spaces for indenting.

**Comment by de-jcup** [comment]
Hello, the plugin uses the standard text editor settings - you can define the indention and spaces for replacement here:
![image](https://user-images.githubusercontent.com/11644753/147733907-5e359f73-5935-4211-ac3b-16c6626a0944.png)

Does this help you?

**Comment by sebalis** [comment]
Yes, it does – thank you.
