### ISSUE TITLE
Eclipse 4.16 06-2020 using Java 8: Cannot complete the install because some dependencies are not satisfiable

### ISSUE THREAD

**Issue by AndreMikulec** [de-jcup/eclipse-bash-editor#248]
Hello,

I am trying to install the Bash Editor using the "Eclipse marketplace" in "Eclipse 4.16 06-2020" eclipse-parallel-2020-06-R-win32-x86_64 that uses Java 8.

What are the installation requirements?

In Eclipse, here is the error, that shows:

```
Cannot complete the install because some dependencies are not satisfiable
  Software being installed: a.jre.javase 14.0.0
  Software currently installed: C/C++ Autotools support 9.11.1.202004012023 (org.eclipse.cdt.autotools.feature.group 9.11.1.202004012023)
  Cannot satisfy dependency:
    From: C/C++ Autotools support 9.11.1.202004012023 (org.eclipse.cdt.autotools.feature.group 9.11.1.202004012023)
    To: org.eclipse.equinox.p2.iu; org.eclipse.tools.templates.freemarker.java11 [1.1.100.202001140305,1.1.100.202001140305]
  Cannot satisfy dependency:
    From: Template Engine Freemarker Support (Java 11) 1.1.100.202001140305 (org.eclipse.tools.templates.freemarker.java11 1.1.100.202001140305)
    To: osgi.ee; (&(osgi.ee=JavaSE)(version=11))
```

Thanks,
Andre Mikulec

**Comment by de-jcup** [comment]
Hello @AndreMikulec ,

this has nothing to do with the bash editor plugin.

In your error output are two entries about "cannot satisfy dependency" which point to the main problem: 
- org.eclipse.tools.templates.freemarker.java11
- osgi.ee; (&(osgi.ee=JavaSE)(version=11))

Both parts are compiled with Java 11 - so not executable with java 8...
They come from the C/C++ auto tools support (not from bash editor)

I would try to start the IDE with Java 11 (should work) by simply setting the JVM settings in `eclipse.ini` accordingly
(you must have a JRE or JDK >=11 installed /available on your system)
see https://wiki.eclipse.org/Eclipse.ini#Specifying_the_JVM

Best wishes Albert

**Comment by AndreMikulec** [comment]
O.K. I will try "a JRE or JDK >=11".

Note, perhaps 
  * JRE 11 or JDK 11, should be mentioned somewhere, as being the minimum version.

**Comment by de-jcup** [comment]
> O.K. I will try "a JRE or JDK >=11".
> 
> Note, perhaps
> 
>     * JRE 11 or JDK 11, should be mentioned somewhere, as being the minimum version.

As mentioned before: Java Version dependency to 11 comes not from my plugin.
