### ISSUE TITLE
Save Actions and "beautysh" on Windows using Git for Windows

### ISSUE THREAD

**Issue by AndreMikulec** [de-jcup/eclipse-bash-editor#252]
@de-jcup

Python "beautysh" on windows does not seem to come with a "beautysh" executable.

In the Preferences -> Bash Editor -> Save Actions -> [x] Execute command on save
Under "External command line tool:"

I have /am_using this "alternate command":

```python.exe -m beautysh.__init__ $filename```

(instead of the default "beautysh -f $filename" that I could not get to work) 
and this "alternate command" seems to work when I SAVE.

From
```
C:\. . .\Python\Python310>python.exe -m beautysh.__init__
usage: __init__.py [--indent-size INDENT_SIZE] [--backup] [--check] [--tab]
                   [--force-function-style FORCE_FUNCTION_STYLE] [--version] [--help]
                   [FILE ...]

A Bash beautifier for the masses, version 6.2.1

positional arguments:
  FILE                  Files to be beautified. This is mandatory. If - is provided as filename, then beautysh reads
                        from stdin and writes on stdout.
```
  
Is that acceptable/correct?  Or, am I missing something?

**Comment by de-jcup** [comment]
@AndreMikulec 

I created #253 to change the default command to `beautysh $filename`.
`beautysh` has unfortunately removed the `-f` parameter in newer versions.

When changing on my Linux machine
![image](https://user-images.githubusercontent.com/11644753/165452293-462b993c-49f7-413c-aaf9-c8de99400c92.png)

to

![image](https://user-images.githubusercontent.com/11644753/165453227-9ba34abb-767c-42d4-8967-8d8f2cf5f54e.png)

pressing button "Validate external tool" does show up 
![image](https://user-images.githubusercontent.com/11644753/165453303-98ca1491-3d55-47c9-aa64-d6df9cdeaca9.png)

So when your "alternate command" does also work with the "Validate external tool" button, then all seems to be correct.
