### ISSUE TITLE
Ctrl+{ collides with default eclipse key binding

### ISSUE THREAD

**Issue by sjaeckel** [de-jcup/eclipse-bash-editor#259]
At first, thanks for your work on the plugin! I recently stumbled over the following...

---

Eclipse Version: 2022-06 (4.24.0)
Eclipse Build id: 20220609-1112
Plugin Version: 2.5.0

---

The default eclipse key binding of `Ctrl+{` is to vertically split the editor.

When the "Auto create ending brackets" option is enabled the behavior looks like this when pressing `Ctrl+{` twice ...

![bash-editor](https://user-images.githubusercontent.com/294374/177736719-2bdd001a-f315-467a-9422-30ec40877a91.gif)

**Comment by de-jcup** [comment]
Hello, I wasn't aware about the shortcut at all. I am currently using
Eclipse Version: 2022-09 (4.25.0)

When looking into preferences it is as you described:
![image](https://user-images.githubusercontent.com/11644753/197006853-3c7837ae-6279-4d16-b08f-3e9c9f1247e3.png)

I had problems to get the shortcut working on my german keyboard... find the correct combination... 

The way to to reproduce/use the problem/feature on a german keyboard is:

Pressing  "CTRL" + "ALT GR" + "7" does split the editor.
And yes this is a problem a bug.. 

Thank you for reporting.

**Comment by de-jcup** [comment]
Hmm...  after looking into the code I was astonished: I am using
```xml
<key
            sequence="M1+7"
            contextId="basheditor.editors.BashEditor.context"
            commandId="basheditor.editor.commands.source.toggleComment"
            schemeId="org.eclipse.ui.defaultAcceleratorConfiguration">	  
		</key>
```
Which does already mean that you have to press only `CTRL` and `7` and nothing more.

Inside the eclipse preferences (Eclipse 2022-12):  bash editor does have exactly this.
![image](https://user-images.githubusercontent.com/11644753/227966956-c29589c8-5e1c-43e8-81c5-6ef8b3c9e1ef.png)

Look at the preferences for splitting windows we got:
![image](https://user-images.githubusercontent.com/11644753/227966075-48a3b75b-c67a-480d-b9d7-7f3e380d377b.png)

Means the configuration of the plugin is correct (CTRL + 7 was a long time the default shortcut for commenting/uncommenting) and the splitting is done not with `7` but with `{`. 
So if this is really a problem, it is more a platform problem: I am using M1 which means `CTRL`.

Sorry, but I will close this issue. If you have still problems here please create an issue at the eclipse platform.

**Comment by sjaeckel** [comment]
Thanks for looking into this!

I was not talking about "toggle comment".

I was talking about the interaction between the "Auto create ending brackets" functionality of the Bash Editor and the "Toggle Split Editor (vertical)" functionality built into Eclipse.

I'm currently on the following version and the issue persists and behaves as described initially.

```
Version: 2023-03 (4.27.0)
Build id: 20230309-1520
```
