### ISSUE TITLE
IF Template with mix of spaces and tabs

### ISSUE THREAD

**Issue by cristalp** [de-jcup/eclipse-bash-editor#266]
While the templates are very useful, the one for IF-ELIF-ELSE contains a mix of spaces and tabs.

I'm not sure whether there is a template variable in Eclipse for indentation, since you (thankfully) suggest in the configuration that the tabs should be replaced by whatever is configured in the Eclipse default settings for text editors. But if there is such a variable, it would be very helpful to have it in the templates. This would mean that a person working with tabs would get tabs in the generated code and a person working with spaces would get spaces in the generated code.

**Comment by de-jcup** [comment]
The templates are just plain text inside the plugin.xml - you can change it inside the IDE and also create additional ones.

For the tab inside the mentioned if-elif-else template I will drop the tab(s).
