### ISSUE TITLE
Bash Editor should not use crlf

### ISSUE THREAD

**Issue by jochenw** [de-jcup/eclipse-bash-editor#268]
Hi,

if I use the Bash Editor to create a shell script on Windows, then the created file will use CRLF as the line terminator, rather than just LF.
The former is cause for trouble, if the file is transferred to Linux/Unix.

Could we

  - Change the editor to **not** use CRLF, possibly as a configurable option?
  - Have Bash Editor create a warning, if the first line ("#!/bin/sh") ends with CRLF?
  - Or, at the very least, provide an action, like "Replace Windows line endingfs with Linux/Unix line endings"?

Thanks,

Jochen

**Comment by de-jcup** [comment]
The answer from https://stackoverflow.com/questions/45144911/change-line-feeds-from-crlf-to-lf-in-eclipse is still valid - you can set text file line delimiter already at 
![image](https://user-images.githubusercontent.com/11644753/227861541-be8622a5-6283-4d9f-9bb2-069f3924b3cc.png)

Is this the solution for your problem?

**Comment by jochenw** [comment]
Thanks, very much! Totally works for me.
