### ISSUE TITLE
Open path in terminal menu entry visible despite preference set to false

### ISSUE THREAD

**Issue by trancexpress** [de-jcup/eclipse-bash-editor#275]
To reproduce:

1. Start in a new workspace.
2. Go to the Bash Editor preference page, Launch, disable the show "Open path in terminal" option.
3. Restart Eclipse.
4. Right-click on some resource in the Package Explorer.
5. Observe the disabled menu entry is visible.

See screen recording:

https://github.com/de-jcup/eclipse-bash-editor/assets/24752155/eb7d0fcb-197c-4be0-86a4-97f4ad937dd7

Additionally it doesn't seem to be possible to set the default for the preference via a `-pluginCustomization` file (https://eclipse.dev/eclipse/platform-core/documents/user_settings/plugin_customization.html)

**Comment by trancexpress** [comment]
Seems like the property tester that controls the menu entry visibility is not loaded when showing the menu. Its loaded when going in the preference page for Bash Editor, or when clicking the menu entry.

**Comment by de-jcup** [comment]
## Testing
### Without restart
I tested with `eclipse 2023-09` + `bash editor plugin 2.9.0` (installed by marketplace) and it works as expected when NOT restarting eclipse:

1. Start in a new workspace.
2. Go to the Bash Editor preference page, Launch, disable the show "Open path in terminal" option.
3. ~Restart Eclipse~
4. Right-click on some resource in the Package Explorer.
5. Observe the disabled menu entry is **NOT** visible.

### Now with restarting eclipse:
#### Preference dialog calls
- Restart eclipse
- Problems as described, the preference is defined as `false` but menu entry still visible
- Entering now preference dialog, open no special dialog, then just close
- menu entry still visible
- Entering now bash editor root preference dialog, then just close
- now menu entry is vanished/no longer visible

#### Bash editor startup
- Restart eclipse
- Problems as described, the preference is defined as `false` but menu entry still visible
- Open a test.sh file inside bash editor
- now menu entry is vanished/no longer visible

## Conclusion

Looking into `OpenPathInTerminalPropertyTester` it uses `BashEditorPreferences.getInstance().isOpenPathInTerminalEnabled();`
which internally only uses the eclipse preference api.

It seems the implementation is correct and that this is more an eclipse problem: As long as there is no plugin interaction (editor, preference pages, etc.) the bash editor preferences seems to be not loaded by eclipse.

Maybe this is related to https://github.com/eclipse-platform/eclipse.platform/issues/523

**Comment by trancexpress** [comment]
Thanks for merging!

**Comment by de-jcup** [comment]
@trancexpress : I just released Version 2.9.1 to eclipse marketplace. It contains your changes

**Comment by trancexpress** [comment]
Great, thank you @de-jcup !
