### ISSUE TITLE
Unexpected syntax error report: "It seems this opening bracket is missing a closing one."

### ISSUE THREAD

**Issue by jam06** [de-jcup/eclipse-bash-editor#39]
Hi There!
And thanks for the 0.9.0 version! this Helps!

here is a problem I noticed with this new version:
the following code makes the bash editor reporting a syntax error: "**It seems this opening bracket is missing a closing one."**

```
declare -A TitleMap

if [ ${#TitleMap[*]} -eq 0 ]
then
    displayerr "Map is empty"
    exit 1
fi

```
My Guess is that the pound sign is taken as a comment and therefore the closing '}' is considered as missing

the exat same problem in the following code: (this code seems surprising but the syntax is perfectly correct. the same error is reported:

```
function array-to-string {
    local _e="$( declare -p ${1} )"
    eval  "local -A _params"=${_e#*=}
    local key
    local separator
    
    for key in ${!_params[@]}
    do
        echo -n "$separator$key=${_params[$key]}"
        separator=" "
    done
}

```

**Comment by de-jcup** [comment]
version 0.9.1 released with bugfix on marketplace

**Comment by jam06** [comment]
Thanks @de-jcup! hyper reactive!
