### ISSUE TITLE
Unexpected error reported when using associative arrays

### ISSUE THREAD

**Issue by jam06** [de-jcup/eclipse-bash-editor#41]
Hi!

With the following code (which is correct), an error is reported on the last line by the bash editor:

the code:

---------------------------------------------------------------
#!/bin/bash

declare -A hostSettings

function display-installation {

        IStatus=${hostSettings[InstallStatus]}
        CStatus=${hostSettings[ConfigStatus]}

        
        #display parameters
        package_Idx=${PackageIdxMap[`basename $package`]}
        display-param-from-file $package/var/${InputFileMap[$package_Idx]} "$context:$host"

}

function display-param-from-file {
}

-----------------------------------------------------------------

By the way if you set the cursor just after the braket (end of the line) at line 5, the closing braket highlighted by the editor is the closing braket at line 7.... it should be the one at the end of the function

Best regards
Jean-marie

**Comment by jam06** [comment]
![capture](https://user-images.githubusercontent.com/31533614/30438681-2019c9bc-9972-11e7-9c51-24784e859d61.PNG)

**Comment by jam06** [comment]
hmmm... version 0.9.3 seems odd to me.... worse than 0.9.1 at least.

the attached file is syntactically correct however some errors are reported ...

[oss-common.zip](https://github.com/de-jcup/eclipse-bash-editor/files/1314230/oss-common.zip)

**Comment by de-jcup** [comment]
@jam06 thank you for the report - you are right there something very odd here. I opened Ticket #52 to solve the problem.

By the way: Would you mind if added the oss-common script to my testscripts in this GIT repository?

**Comment by de-jcup** [comment]
@jam06 Version 0.10.0 is now available at eclipse marketplace - your oss-common script has no longer failures with this version.
I wrote a test that ensures all testscripts in a special subfolder contains no failures. I would like to add your script into this folder inside the GIT repo. Would this be okay for you?

**Comment by jam06** [comment]
Hello Albert!

Very sorry for my late reply, your mails were in my Junk Email folder…. Oops!

No problem for using my file oss-common.sh (just one thing, please rename it with the name you want but don’t use oss-common, thanks)

I’m using your late version with no problem so far! Many thanks for the work.

Best regards;
Jean-marie

**Comment by de-jcup** [comment]
@jam06 - thank you. Added you script with name` bugfix_41_4_bigscript.sh` in last commit to a special testscript folder . So it will always automatically tested by every build now.
