### ISSUE TITLE
Very short undo history size

### ISSUE THREAD

**Issue by mauri-melato** [de-jcup/eclipse-bash-editor#65]
Playing with the editor it seems to have a very short undo history size, actually around 25 editing actions.
This settings it's specific of the bash editor and not inherited from the `General -> Editors -> Text Editors` settings of Eclipse.

Needless to say this limit has a strong impact on real working sessions. 

Thanks

**Comment by de-jcup** [comment]
Thank you for this information! This bug is also inside EGradle editor and descendands so I created there a bug too: https://github.com/de-jcup/egradle/issues/308 .

Will be fixed.

**Comment by mauri-melato** [comment]
Thanks!

**Comment by de-jcup** [comment]
@mauri-melato You are welcome :-) I hopefully will release Version 1.1.0 in the next days.
