### ISSUE TITLE
Why `cp` is not highlighted?

### ISSUE THREAD

**Issue by paulvi** [de-jcup/eclipse-bash-editor#67]
Why `cp` is not highlighted? But `mkdir` is.
Where is list of shell commands known for the plugin?

![image](https://user-images.githubusercontent.com/1614482/32257216-bbc8ef54-beee-11e7-9d1e-15d47d36b006.png)

**Comment by de-jcup** [comment]
The wellknown GNU keywords are defined at

https://github.com/de-jcup/eclipse-bash-editor/blob/master/basheditor-plugin/src/main/java-eclipse/de/jcup/basheditor/document/keywords/BashGnuCommandKeyWords.java

I simply forgot the `cp` command...

If you got more standard commands which could be highlighted as well, please tell me.
