### ISSUE TITLE
User having problems with Eclipse Oxygen 4.7.1a

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-bash-editor#76]
This is an own issue for the question found in https://github.com/de-jcup/eclipse-bash-editor/issues/16#issuecomment-344749915 @cwilliamson62 wrote:

> I cannot find bash editor in the list of internal editors after installation. I cannot see any bash in the eclipse preferences. I don't know how to open a file with bash editor because it is not a choice. I am on Eclipse version Oxygen.1a Release (4.7.1a). Is there some prerequisite or something that I am missing? Thanks a ton for any help you might offer.
> Chris

**Comment by de-jcup** [comment]
Please check your installation did not fail by opening:
Mainmenu: Help->About eclipse:

![image](https://user-images.githubusercontent.com/11644753/32895060-13776a90-cadf-11e7-8907-6d03ded6ab67.png)

Press the` Installation details` button

Now you should see following:
![image](https://user-images.githubusercontent.com/11644753/32895114-46010598-cadf-11e7-973b-898634004c1b.png)

So this means you have sucessfully installed bash editor.
@cwilliamson62 : please tell me if bash editor is installed like seen in picture above or not, so I can give you further help.

**Comment by cwilliamson62** [comment]
@de-jcup: Yes sir it is. Also, not sure if it matters, but I am running on a Mac. Thanks you so much for your help!

**Comment by de-jcup** [comment]
@cwilliamson62 : I asked a colleague to install bash-editor via eclipse marketplace client on his mac. It worked out of the box. He was using Java 9 to startup eclipse. Eclipse was oxygen V4.7.1a as well.

I am using bash-editor on windows 7 and linux with GDK by myself and it all works.

# Install from scratch
I tried a complete installation from scratch on linux:
- downloaded https://www.eclipse.org/downloads/packages/eclipse-ide-java-developers/oxygen1a
  or more explicit: http://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/oxygen/1a/eclipse-java-oxygen-1a-linux-gtk-x86_64.tar.gz
- then started the downloaded variant on a fresh workspace with dedicated java - I used openjdk version "1.8.0_151" for this
- then opened eclipse market place client (Main menu: Help->Eclipse Marketplace... )and entered "bash" inside find-text field then pressed ENTER key to start search. After some seconds "Bash editor 1.2.1" appeared on screen and I pressed the "Install" button. Then selected "I accept the terms of the license aggreement" (Apache 2.0). After this I pressed "Finish" button
![grafik](https://user-images.githubusercontent.com/11644753/32907979-628b31fc-cb02-11e7-8b38-b9a5ffcdb114.png)
Now pressing "Install anyway" - sorry I got no certificate at the moment.
![grafik](https://user-images.githubusercontent.com/11644753/32908005-820e30c4-cb02-11e7-912b-6cd261652853.png)
Now press "Restart now"
-  After a while eclipse has restarted, started to create a new project:
![grafik](https://user-images.githubusercontent.com/11644753/32908074-bf0dd830-cb02-11e7-81ae-8bc0ac2b9d2e.png)
The pressed "Finish" again.
- After project is created I added a new file there:
![grafik](https://user-images.githubusercontent.com/11644753/32908119-e4b5d22c-cb02-11e7-8604-b5ca3a68e437.png)
Then press "Finish" again
- After wizard is closed the new file was automatically opened with bash-editor:
![grafik](https://user-images.githubusercontent.com/11644753/32908230-38fde374-cb03-11e7-8cd5-05579af0b41d.png)
- You can reopen files also with right click on Navigator/Package explorer view and "Open with... bash-editor"

**Comment by de-jcup** [comment]
I am closing the issue now  - if there is still support needed, please comment here for reopening.

**Comment by o771** [comment]
FWIW, I have the same problem on Indigo 3.8.1 running on Ubuntu 14.04LTS. I've successfully installed Bash Editor 1.5.3 from Marketplace, using the Marketplace client, and it shows up as installed. No errors were reported during the installation. I've restarted Eclipse. But Bash Editor is not listed as an available internal editor, e.g., when trying to associate *.sh. Nor does it show up on the Open With context menu, even under Other... I've tried uninstalling/reinstalling Bash Editor. I don't see any related errors in the Error Log.

**Comment by de-jcup** [comment]
Hello @o771,

I had some similar issue years ago, I installed a plugin and it was not working. The reason at this time was that the class version was higher than the JRE I started eclipse with and I also did not found eclipse logs in this case.

The official minimum requirement for running basheditor plugin is  "Eclipse Neon" (see https://marketplace.eclipse.org/content/bash-editor or look at following picture:)
![image](https://user-images.githubusercontent.com/11644753/39577020-7001fa70-4ee0-11e8-9055-d9595f89c299.png). Starting with eclipse neon the minimum requirement for eclipse itself is Java 8. 

I don't know if such an old version of eclipse is ready to run bash editor plugin. I have never tested it.  Maybe its only an issue with the JRE version but I don't know.

IMHO you could do following:

**Solution A:**
Just download a new version of your desired eclipse package directly from https://www.eclipse.org/downloads/eclipse-packages/ unzip it and start it with a java version >=8.
Then bash editor will work - I am using bash editor with an Ubuntu based distribution as well on Eclipse Oxygen 3a and have no problems.

**Solution B:**
Ensure you start your older eclipse version with a JRE >=8 and try out if it works.


I would prefer **Solution A** because you got so many benefits at all when you are using the newest (and also stable) Version of eclipse (currently oxygen3a). Normally I am a fan of using the linux package manager and the software versions Ubuntu comes with, but for eclipse I don't like it at all ( I tried it out ....) because versions are often very old and eclipse itself does update itself automatically (if you want).

The eclipse 4.x versions are no longer slow and the eclipse 3.8. version has only the features comparable to 4.2 and development is no longer ongoing (see https://en.wikipedia.org/wiki/Eclipse_(software)#cite_note-33)
Also eclipse packages downloaded, must be simply unpacked and then started and working out of the box.
