### ISSUE TITLE
Avoid highlighting and syntax checking within 'here documents' blocks 

### ISSUE THREAD

**Issue by mauri-melato** [de-jcup/eclipse-bash-editor#78]
An _heredoc_ block include a multiline block of text that  should be probably treated as a literal string.

An example: 

```sh
cat << EOF
free text
sometimes even snippets of code..

# No highlight here
if [ -z "${MY_VAR}" ]; then
  echo "empty var"
fi
EOF

# highlight here
if [ -z "${MY_VAR}" ]; then
  echo "empty var"
fi
```
Commands might also follow the heredoc string delimiter and you would probably want to have syntax highlighting there, e.g. `cat << EOF | grep -i TargetString --color`

**Comment by de-jcup** [comment]
This is not only a enhancement for syntax highlighting but is a bug inside validation:

![image](https://user-images.githubusercontent.com/11644753/33308924-a83a8aea-d41c-11e7-94f9-7223476ab88e.png)

**Comment by mauri-melato** [comment]
Yep with syntax checking I meant the validation part.
Thanks.

**Comment by de-jcup** [comment]
A special syntax highlighting is also needed -e.g. to prevent wrong String handling in colors:

![image](https://user-images.githubusercontent.com/11644753/33318556-49d983f6-d43b-11e7-943f-fc127d5d0df9.png)

**Comment by de-jcup** [comment]
Hello @mauri-melato I have finished the syntax highlighting improvement now. I was currently not able to provide syntax highlighting for following commands as suggested and created https://github.com/de-jcup/eclipse-bash-editor/issues/79 for this - maybe in future this will be implemented.

The syntax highlighting (with version 1.3.0) works for here-docs as shown in next pictures:

# Dark theme:
![image](https://user-images.githubusercontent.com/11644753/33374798-e0671e24-d507-11e7-8e6f-17b063f79487.png)

# White theme:
![image](https://user-images.githubusercontent.com/11644753/33374837-07429f96-d508-11e7-956d-dbe1642658eb.png)

**Comment by mauri-melato** [comment]
Thanks Albert, good job.
