### ISSUE TITLE
Make bash scripts excecutable in eclipse

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-bash-editor#81]
Sometimes it would be nice to directly start bash scripts from eclipse - of course also with parameters etc.

**Comment by de-jcup** [comment]
Ok. So I ll keep it simple and close this issue. Thank you @paulvi

**Comment by paulvi** [comment]
Would be nice to point users in wiki

**Comment by de-jcup** [comment]
Mentioned at https://github.com/de-jcup/eclipse-bash-editor/wiki/FAQ#how-can-i-execute-shell-scripts-with-bash-editor
