### ISSUE TITLE
for do done block being marked as error

### ISSUE THREAD

**Issue by kc7bfi** [de-jcup/eclipse-bash-editor#84]
The following is my code:

```
for i in `seq 1 16`; do
if [ -d "/disk$i" ]; then
  if [ ! -d "/disk$i/vicads" ]; then
    echo "Creating /disk$i/vicads"
  fi
fi
done
```

the bash editor is reporting the error: 

`This 'Do' is not correct closed. A 'Done' is missing	Basheditor script problem`

Any idea what I'm doing wrong? David

**Comment by de-jcup** [comment]
Hello David (@kc7bfi) , in the former commit https://github.com/de-jcup/eclipse-bash-editor/commit/f36c55777bebd1476d4e47cfb6d20be5359ff7a5 I added your code snippet to a testfolder which is always validated on build. No failures.

I also tried out your code snippet in Bash-Editor (current Version is 1.3.0):

![grafik](https://user-images.githubusercontent.com/11644753/33500330-b7b9cf4e-d6d8-11e7-8205-f4cc6a7dc142.png)

When saving the editor file the validation is triggered and I did this multiple times - the editor shows now validation errors

Only when I am doing a failure like changinge `done` to `doneX` the error appears:
![grafik](https://user-images.githubusercontent.com/11644753/33500417-059dfad2-d6d9-11e7-9e32-73d01aea5687.png)

So maybe you are using an older version of bash editor? If you got still problems you could attach your problematic script to the issue. By the way: validation of bash editor is done not by bash shell but bash editors simple parser. So you could try out if the error occurrs with a bash call too. If you still cannot get on with it and your script is working well you can turn off the validation of bash edior in preferences:

![grafik](https://user-images.githubusercontent.com/11644753/33500592-a3cae6e8-d6d9-11e7-8738-cbd3ec9c5640.png)

**Comment by de-jcup** [comment]
I am closing the issue now  - if there is still support needed, please comment here for reopening.
