### ISSUE TITLE
Cannot see fi for https://get.docker.com/ script

### ISSUE THREAD

**Issue by paulvi** [de-jcup/eclipse-bash-editor#86]
> This 'if' statement is not correct closed. A 'fi' is missing

for script at https://get.docker.com/

![image](https://user-images.githubusercontent.com/1614482/33746632-6d863ac2-dbf9-11e7-93e5-c4c2f4c603ba.png)

**Comment by de-jcup** [comment]
Also syntax highlighting failed. The heredoc combination of` cat >&2 <<-'EOF' ... EOF `fails
