### ISSUE TITLE
Configurable problem level

### ISSUE THREAD

**Issue by paulvi** [de-jcup/eclipse-bash-editor#87]
An error in script, should not make whole project as red (containing error)

Or simply put, as a user I would like to be able to ignore all such Problems, so they don't appear

![image](https://user-images.githubusercontent.com/1614482/33749483-ed1d0e8c-dc08-11e7-8d7a-c25965aef498.png)

**Comment by de-jcup** [comment]
Its now possible to configure the error level which will be used for eclipse markers:

![image](https://user-images.githubusercontent.com/11644753/33789907-30c482be-dc7c-11e7-907a-837574ed981a.png)

**Comment by de-jcup** [comment]
@paulvi you can update from marketplace - 1.4.0 is available and there you can configure the error level to warning...
