### ISSUE TITLE
Wrong validation errors on bigger script

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-bash-editor#91]
At #90 some validation errors occurred inside bash editor when opening a bigger script.

**Comment by de-jcup** [comment]
@zeroincombenze At #90 you described your problems with bash editor on a bigger script you wrote.

Is it possible to get the complete script? I would like to integrate it into my test script folder which is always scanned on build having no errors inside at all.

If you don't like to post the full code, you code also do some obfuscations…
I would like to fix the problems you described.

**Comment by de-jcup** [comment]
Found one problem: The "$x}" results into one token instead of two so the closing curly bracket is not recognized by token parser... so this seems to be a problem in variable recognition (syntax highlighting is also wrong but not a big problem.)

![image](https://user-images.githubusercontent.com/11644753/34075224-5a625b92-e2c0-11e7-980a-c27df56328ba.png)

**Comment by zeroincombenze** [comment]
Hello,
I uploaded the bash script. In my eclipse editor error is at line 2306.
The other errors printed above at line 2939 and 3400 are solved after upgrade  with 1.4.1

[lisa.txt](https://github.com/de-jcup/eclipse-bash-editor/files/1565572/lisa.txt)
